/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Basicas.Disciplina;
import Excecoes.ExcecaoNome;
import Negocio.Fachada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class jofCadastroDisciplina extends javax.swing.JInternalFrame {

    /**
     * Creates new form jofCadastroDisciplina
     */
    Disciplina disciplina; 
    Fachada fachada; 
    public jofCadastroDisciplina() {
        this.fachada = Fachada.getInstance();
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbCriar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmenta = new javax.swing.JTextPane();

        setTitle("Cadastro Disciplina");
        setMaximumSize(new java.awt.Dimension(106, 34));
        setMinimumSize(new java.awt.Dimension(106, 34));
        setPreferredSize(new java.awt.Dimension(106, 34));
        getContentPane().setLayout(null);
        getContentPane().add(jtNome);
        jtNome.setBounds(70, 10, 150, 30);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 20);

        jLabel3.setText("Ementa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 80, 20);

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNovo);
        jbNovo.setBounds(20, 220, 90, 30);

        jbCriar.setText("Criar");
        jbCriar.setEnabled(false);
        jbCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCriar);
        jbCriar.setBounds(130, 220, 90, 30);

        jbLimpar.setText("Limpar");
        jbLimpar.setEnabled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpar);
        jbLimpar.setBounds(20, 270, 90, 30);

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jbFechar);
        jbFechar.setBounds(130, 270, 90, 30);

        jScrollPane1.setViewportView(jtEmenta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 60, 150, 150);

        setBounds(0, 0, 248, 349);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        String nome = new String();
        String ementa = new String();

        try{
            nome = jtNome.getText();
            ementa = jtEmenta.getText();
            if(ementa.length() > 0){
                disciplina = new Disciplina(fachada.retornaProximoCodigoDisciplina(), nome, ementa);
                jbCriar.setEnabled(true);
                jbLimpar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Ementa não pode ser vazia");
            }
            
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(rootPane, "A disciplina não pode está vazia");
        }

    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarActionPerformed
        try {
            // TODO add your handling code here:
            fachada.insereDisciplina(disciplina);
            JOptionPane.showMessageDialog(rootPane, "Disciplina "+ disciplina.getNome() + "criada com sucesso");
            disciplina = null;
            jtNome.setText("");
            jtEmenta.setText("");
            jbCriar.setEnabled(false);
            jbLimpar.setEnabled(false);
        } catch (ExcecaoNome ex) {
            Logger.getLogger(jofCadastroDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            
        }
    }//GEN-LAST:event_jbCriarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        disciplina = null;
        jtNome.setText("");
        jtEmenta.setText("");
        jbCriar.setEnabled(false);
        jbLimpar.setEnabled(false);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCriar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JTextPane jtEmenta;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
