/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Basicas.Aluno;
import Negocio.Fachada;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthur
 */
public class jofConsultaAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form jofConsultaAluno
     */
    
    Fachada fachada; 
    private DefaultTableModel dtmAlunos;
    public jofConsultaAluno(Fachada fachada, int tipoTela) {
        
        // De acordo com o tipo de tela, iremos definir 1 - consulta e 2 para alterar. 
        initComponents();
        this.fachada = fachada;
        
        dtmAlunos = (DefaultTableModel) jtAluno.getModel();
        for (Aluno aluno : fachada.retornaListaAluno()) {
            Object[] dados = {aluno.getMatricula(), aluno.getNome(), aluno.getDataDeNascimento(), aluno.getNomeUsuario(), aluno.getPerido()};
            dtmAlunos.addRow(dados);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAluno = new javax.swing.JTable();
        jpAlteraAluno = new javax.swing.JPanel();
        jpConsultaAluno = new javax.swing.JPanel();
        jbExcluirAluno = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();

        setTitle("Consulta Alunos");
        setMinimumSize(new java.awt.Dimension(705, 407));
        getContentPane().setLayout(null);

        jtAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", "Data Nascimento", "Nome Usuário", "Período"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtAluno);

        javax.swing.GroupLayout jpAlteraAlunoLayout = new javax.swing.GroupLayout(jpAlteraAluno);
        jpAlteraAluno.setLayout(jpAlteraAlunoLayout);
        jpAlteraAlunoLayout.setHorizontalGroup(
            jpAlteraAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpAlteraAlunoLayout.setVerticalGroup(
            jpAlteraAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jpAlteraAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAlteraAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 700, 320);

        jbExcluirAluno.setText("Exclui Aluno");
        jbExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirAlunoActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaAlunoLayout = new javax.swing.GroupLayout(jpConsultaAluno);
        jpConsultaAluno.setLayout(jpConsultaAlunoLayout);
        jpConsultaAlunoLayout.setHorizontalGroup(
            jpConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaAlunoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jbExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jpConsultaAlunoLayout.setVerticalGroup(
            jpConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExcluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jpConsultaAluno);
        jpConsultaAluno.setBounds(0, 0, 700, 50);

        setBounds(0, 0, 719, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
        
        limpaTabela();
        for (Aluno aluno : fachada.retornaListaAluno()) {
            Object[] dados = {aluno.getMatricula(), aluno.getNome(), aluno.getDataDeNascimento(), aluno.getNomeUsuario(), aluno.getPerido()};
            dtmAlunos.addRow(dados);
        }
        
    }//GEN-LAST:event_jbAtualizarActionPerformed

    
    public void limpaTabela(){
        
        if (dtmAlunos.getRowCount() > 0){
            for (int i=0;i<=dtmAlunos.getRowCount();i++){
                dtmAlunos.removeRow(0);
            }            
        }
    }
    
    private void jbExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirAlunoActionPerformed
        // TODO add your handling code here:
        
        if(jtAluno.getSelectedRow() != -1){
            
           if(fachada.verificaAlunoExiste(jtAluno.getValueAt(jtAluno.getSelectedRow(), 0).toString())){           
           fachada.removeAluno(jtAluno.getValueAt(jtAluno.getSelectedRow(), 0).toString());
           dtmAlunos.removeRow(jtAluno.getSelectedRow());
           JOptionPane.showMessageDialog(rootPane, "Aluno Excluido com Sucesso!");
           }else{
               JOptionPane.showMessageDialog(rootPane, "Este Aluno não existe, favor atualizar a Tabela");
           }            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
        }
        
    }//GEN-LAST:event_jbExcluirAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluirAluno;
    private javax.swing.JButton jbSair;
    private javax.swing.JPanel jpAlteraAluno;
    private javax.swing.JPanel jpConsultaAluno;
    private javax.swing.JTable jtAluno;
    // End of variables declaration//GEN-END:variables
}
