/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Basicas.Disciplina;
import Negocio.Fachada;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthur
 */
public class jofConsultaDisciplina extends javax.swing.JInternalFrame {

    /**
     * Creates new form jofConsultaDisciplina
     */
    
    Fachada fachada; 
    
    private DefaultTableModel dtmDisciplina;
    
    public jofConsultaDisciplina(Fachada fachada, int tipoTela) {
        initComponents();
        this.fachada = fachada; 
       dtmDisciplina  = (DefaultTableModel) jtDisciplina.getModel();
        
        for (Disciplina disciplina : fachada.retornaListaDisciplina()) {
            Object[] dados = {disciplina.getcodigo(), disciplina.getNome()};
            dtmDisciplina.addRow(dados);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAlteraDisciplina = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDisciplina = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaEmenta = new javax.swing.JTextArea();
        jpConsultaDisciplina = new javax.swing.JPanel();
        jbExcluirAluno = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();

        setTitle("Consulta Disciplina");
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jpAlteraDisciplinaLayout = new javax.swing.GroupLayout(jpAlteraDisciplina);
        jpAlteraDisciplina.setLayout(jpAlteraDisciplinaLayout);
        jpAlteraDisciplinaLayout.setHorizontalGroup(
            jpAlteraDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jpAlteraDisciplinaLayout.setVerticalGroup(
            jpAlteraDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jpAlteraDisciplina);
        jpAlteraDisciplina.setBounds(20, 10, 540, 50);

        jtDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDisciplinaMouseClicked(evt);
            }
        });
        jtDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDisciplinaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtDisciplina);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 310, 200);

        jtaEmenta.setEditable(false);
        jtaEmenta.setColumns(20);
        jtaEmenta.setRows(5);
        jScrollPane1.setViewportView(jtaEmenta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(336, 130, 230, 200);

        jbExcluirAluno.setText("Exclui Disciplina");
        jbExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirAlunoActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaDisciplinaLayout = new javax.swing.GroupLayout(jpConsultaDisciplina);
        jpConsultaDisciplina.setLayout(jpConsultaDisciplinaLayout);
        jpConsultaDisciplinaLayout.setHorizontalGroup(
            jpConsultaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jpConsultaDisciplinaLayout.setVerticalGroup(
            jpConsultaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExcluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jpConsultaDisciplina);
        jpConsultaDisciplina.setBounds(20, 70, 527, 45);

        setBounds(0, 0, 586, 368);
    }// </editor-fold>//GEN-END:initComponents

    private void jbExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirAlunoActionPerformed
        // TODO add your handling code here:
         
        if(jtDisciplina.getSelectedRow() != -1){

            if(fachada.verificaDisciplinaExiste(jtDisciplina.getValueAt(jtDisciplina.getSelectedRow(), 1).toString())){
                Disciplina disciplinaAUX = fachada.buscaDisciplina(Integer.parseInt(jtDisciplina.getValueAt(jtDisciplina.getSelectedRow(), 0).toString()));
                if(fachada.verificaDesciplinaPossuiTurma(disciplinaAUX.getcodigo())){
                    JOptionPane.showMessageDialog(rootPane, "Disciplina Não Pode ser excluida, pois está vinculada a uma Turma!");
                }else{
                fachada.removeDisciplina(disciplinaAUX.getcodigo());
                dtmDisciplina.removeRow(jtDisciplina.getSelectedRow());
                jtaEmenta.setText("");
                JOptionPane.showMessageDialog(rootPane, "Disciplina Excluida com Sucesso!");
                }               
            }else{
                JOptionPane.showMessageDialog(rootPane, "Esta Disciplina não existe, favor atualizar a Tabela!");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        }

    }//GEN-LAST:event_jbExcluirAlunoActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:

        limpaTabela();
        for (Disciplina disciplina : fachada.retornaListaDisciplina()) {
            Object[] dados = {disciplina.getcodigo(), disciplina.getNome()};
            dtmDisciplina.addRow(dados);
        }

    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jtDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDisciplinaKeyReleased
        // TODO add your handling code here:
        
        if(jtDisciplina.getSelectedRow() != -1){
            if(fachada.verificaDisciplinaExiste(jtDisciplina.getValueAt(jtDisciplina.getSelectedRow(), 1).toString())){
                Disciplina disciplinaAUX = fachada.buscaDisciplina(Integer.parseInt(jtDisciplina.getValueAt(jtDisciplina.getSelectedRow(), 0).toString()));
                jtaEmenta.setText(disciplinaAUX.getEmenta());
                
            }
        }
        
    }//GEN-LAST:event_jtDisciplinaKeyReleased

    private void jtDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDisciplinaMouseClicked
        // TODO add your handling code here:
        
        if(jtDisciplina.getSelectedRow() != -1){
            if(fachada.verificaDisciplinaExiste(jtDisciplina.getValueAt(jtDisciplina.getSelectedRow(), 1).toString())){
                Disciplina disciplinaAUX = fachada.buscaDisciplina(Integer.parseInt(jtDisciplina.getValueAt(jtDisciplina.getSelectedRow(), 0).toString()));
                jtaEmenta.setText(disciplinaAUX.getEmenta());
                
            }
        }
        
    }//GEN-LAST:event_jtDisciplinaMouseClicked

    public void limpaTabela(){
        
        if (dtmDisciplina.getRowCount() > 0){
            for (int i=0;i<=dtmDisciplina.getRowCount();i++){
                dtmDisciplina.removeRow(0);
            }            
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluirAluno;
    private javax.swing.JButton jbSair;
    private javax.swing.JPanel jpAlteraDisciplina;
    private javax.swing.JPanel jpConsultaDisciplina;
    private javax.swing.JTable jtDisciplina;
    private javax.swing.JTextArea jtaEmenta;
    // End of variables declaration//GEN-END:variables
}
