/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Basicas.Disciplina;
import Basicas.Professor;
import Basicas.Turma;
import Negocio.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class jofCadastroTurma extends javax.swing.JInternalFrame {

    /**
     * Creates new form jofCadastroTurma
     */
    
    Fachada fachada;
    Turma turma;
    
    public jofCadastroTurma(Fachada fachada) {
        initComponents();
        
        this.fachada = fachada;
        
        for (Disciplina dis : this.fachada.retornaListaDisciplina()) {
            cbDisciplina.addItem(dis);
        }
        
        for (Professor prof : this.fachada.retornaListaProfessor()) {
            cbProfessor.addItem(prof);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPreencheProf = new javax.swing.ButtonGroup();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtCapdaTurma = new javax.swing.JTextField();
        cbDisciplina = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jrPreencher = new javax.swing.JRadioButton();
        jrNaoPreencher = new javax.swing.JRadioButton();
        cbProfessor = new javax.swing.JComboBox<>();
        jbLimpar = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbCriar = new javax.swing.JButton();

        setTitle("Cadastro Turma");
        getContentPane().setLayout(null);
        getContentPane().add(jtNome);
        jtNome.setBounds(20, 40, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Professor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 100, 90, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 80, 20);
        getContentPane().add(jtCapdaTurma);
        jtCapdaTurma.setBounds(220, 40, 150, 30);

        getContentPane().add(cbDisciplina);
        cbDisciplina.setBounds(20, 130, 120, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Capacidade da Turma");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 10, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Disciplina");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 90, 60, 30);

        btgPreencheProf.add(jrPreencher);
        jrPreencher.setText("Preencher");
        jrPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPreencherActionPerformed(evt);
            }
        });
        getContentPane().add(jrPreencher);
        jrPreencher.setBounds(350, 110, 100, 23);

        btgPreencheProf.add(jrNaoPreencher);
        jrNaoPreencher.setText("Não Preencher");
        getContentPane().add(jrNaoPreencher);
        jrNaoPreencher.setBounds(350, 150, 120, 23);

        cbProfessor.setMinimumSize(new java.awt.Dimension(28, 20));
        cbProfessor.setPreferredSize(new java.awt.Dimension(28, 20));
        getContentPane().add(cbProfessor);
        cbProfessor.setBounds(210, 130, 120, 20);

        jbLimpar.setText("Limpar");
        jbLimpar.setEnabled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpar);
        jbLimpar.setBounds(230, 210, 80, 30);

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jbFechar);
        jbFechar.setBounds(330, 210, 80, 30);

        jbNovo.setText("Novo");
        jbNovo.setMaximumSize(new java.awt.Dimension(63, 23));
        jbNovo.setMinimumSize(new java.awt.Dimension(63, 23));
        jbNovo.setPreferredSize(new java.awt.Dimension(63, 23));
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNovo);
        jbNovo.setBounds(130, 210, 80, 30);

        jbCriar.setText("Criar");
        jbCriar.setEnabled(false);
        jbCriar.setMaximumSize(new java.awt.Dimension(63, 23));
        jbCriar.setMinimumSize(new java.awt.Dimension(63, 23));
        jbCriar.setPreferredSize(new java.awt.Dimension(63, 23));
        jbCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCriar);
        jbCriar.setBounds(30, 210, 80, 30);

        setBounds(0, 0, 479, 297);
    }// </editor-fold>//GEN-END:initComponents

    private void jrPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPreencherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        turma = null;
        jbCriar.setEnabled(false);
        jbLimpar.setEnabled(false);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        String nome = new String();
        int quantidade;
        

        try{
            nome = jtNome.getText();
            quantidade = Integer.parseInt(jtCapdaTurma.getText());
            if(!(fachada.verificaTurmaExiste(nome))){
                Disciplina disc = (Disciplina) cbDisciplina.getSelectedItem();
                if(jrPreencher.isSelected()){
                    Professor prof = (Professor) cbProfessor.getSelectedItem();
                    turma = new Turma(fachada.retornaProximoIdTurma(), nome, prof.getId(), quantidade, disc.getcodigo());
                    jbCriar.setEnabled(true);
                    jbLimpar.setEnabled(true);
                }else if(jrNaoPreencher.isSelected()){
                    turma = new Turma(fachada.retornaProximoIdTurma(), nome, quantidade, disc.getcodigo());
                    jbCriar.setEnabled(true);
                    jbLimpar.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Selecione uma Opção");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Nome de Turma Já Existe");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(rootPane, "Erro " + e);
        }
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarActionPerformed
        // TODO add your handling code here:
        fachada.insereTurma(turma);
        JOptionPane.showMessageDialog(rootPane, "Turma Cadastrado");
        turma = null;
        jbCriar.setEnabled(false);
        jbLimpar.setEnabled(false);
    }//GEN-LAST:event_jbCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPreencheProf;
    private javax.swing.JComboBox<Object> cbDisciplina;
    private javax.swing.JComboBox<Object> cbProfessor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCriar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JRadioButton jrNaoPreencher;
    private javax.swing.JRadioButton jrPreencher;
    private javax.swing.JTextField jtCapdaTurma;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
