/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Basicas.Aluno;
import Basicas.Disciplina;
import Basicas.Rendimento_Escolar;
import Basicas.Turma;
import Negocio.Fachada;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthur
 */
public class jofEnvioAtividade extends javax.swing.JInternalFrame {

    /**
     * Creates new form jofEnvioAtividade
     */
    
    private Fachada fachada;
    private Aluno aluno;
    private DefaultTableModel dtmTurmas;
    
    public jofEnvioAtividade(Fachada fachada, Aluno aluno) {
        initComponents();
        
        this.fachada = fachada; 
        this.aluno = aluno;
        
        dtmTurmas = (DefaultTableModel) jtTurma.getModel();
        
        limpaTabela();
        limpaCampos();
        ativaBotao();
        
        for (Turma turma : fachada.retornaListaTurmaAluno(aluno)) {
                Rendimento_Escolar rendEsco = fachada.buscaRendimentoEscolar(aluno.getId(), turma.getId());
                Object[] dados = {turma.getNome(), turma.getProfessor() != -1 ? fachada.buscaProfessor(turma.getProfessor()).getNome() : " ", fachada.buscaDisciplina(turma.getDisciplina()).getNome(), rendEsco.getStatus()};
                dtmTurmas.addRow(dados);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEnviar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTurma = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAtv3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAtv1 = new javax.swing.JTextArea();
        jrbEnviar3 = new javax.swing.JRadioButton();
        jrbEnviar1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtAtv4 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtAtv2 = new javax.swing.JTextArea();
        jrbEnviar4 = new javax.swing.JRadioButton();
        jrbEnviar2 = new javax.swing.JRadioButton();
        jbAtualizar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbEnviaAtividade = new javax.swing.JButton();

        setTitle("Envio Atividades");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jtTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Professor", "Disciplina", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTurmaMouseClicked(evt);
            }
        });
        jtTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTurmaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtTurma);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 660, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 330, 660, 160);

        jLabel1.setText("Atividade 3 ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 170, 80, 14);

        jtAtv3.setColumns(20);
        jtAtv3.setRows(5);
        jScrollPane2.setViewportView(jtAtv3);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 210, 170, 100);

        jLabel2.setText("Atividade 1 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 20, 80, 14);

        jtAtv1.setColumns(20);
        jtAtv1.setRows(5);
        jScrollPane3.setViewportView(jtAtv1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(130, 50, 170, 100);

        btgEnviar.add(jrbEnviar3);
        jrbEnviar3.setText("Enviar");
        jrbEnviar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnviar3ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbEnviar3);
        jrbEnviar3.setBounds(200, 165, 55, 23);

        btgEnviar.add(jrbEnviar1);
        jrbEnviar1.setText("Enviar");
        jrbEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnviar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbEnviar1);
        jrbEnviar1.setBounds(200, 15, 55, 23);

        jLabel3.setText("Atividade 4");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 170, 80, 14);

        jtAtv4.setColumns(20);
        jtAtv4.setRows(5);
        jScrollPane4.setViewportView(jtAtv4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(330, 210, 170, 100);

        jLabel4.setText("Atividade 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 20, 80, 14);

        jtAtv2.setColumns(20);
        jtAtv2.setRows(5);
        jScrollPane5.setViewportView(jtAtv2);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(330, 50, 170, 100);

        btgEnviar.add(jrbEnviar4);
        jrbEnviar4.setText("Enviar");
        jrbEnviar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnviar4ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbEnviar4);
        jrbEnviar4.setBounds(420, 165, 55, 23);

        btgEnviar.add(jrbEnviar2);
        jrbEnviar2.setText("Enviar");
        jrbEnviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnviar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jrbEnviar2);
        jrbEnviar2.setBounds(420, 15, 55, 23);

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAtualizar);
        jbAtualizar.setBounds(10, 230, 75, 30);

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        getContentPane().add(jbSair);
        jbSair.setBounds(530, 153, 110, 30);

        jbEnviaAtividade.setText("Enviar Atividade");
        jbEnviaAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviaAtividadeActionPerformed(evt);
            }
        });
        getContentPane().add(jbEnviaAtividade);
        jbEnviaAtividade.setBounds(10, 110, 111, 30);

        setBounds(0, 0, 677, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEnviar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEnviar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEnviar3ActionPerformed

    private void jrbEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEnviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEnviar1ActionPerformed

    private void jrbEnviar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEnviar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEnviar4ActionPerformed

    private void jrbEnviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEnviar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEnviar2ActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
        
       
        limpaTabela();
        
               
        for (Turma turma : fachada.retornaListaTurmaAluno(aluno)) {
                Rendimento_Escolar rendEsco = fachada.buscaRendimentoEscolar(aluno.getId(), turma.getId());
                Object[] dados = {turma.getNome(), turma.getProfessor() != -1 ? fachada.buscaProfessor(turma.getProfessor()).getNome() : " ", fachada.buscaDisciplina(turma.getDisciplina()).getNome(), rendEsco.getStatus()};
                dtmTurmas.addRow(dados);
        }
        
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbEnviaAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviaAtividadeActionPerformed
        // TODO add your handling code here:
        if(jtTurma.getSelectedRow() != -1){
            Rendimento_Escolar rendEsco = fachada.buscaRendimentoEscolar(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId());
            if(jrbEnviar1.isSelected()){
                fachada.insereAtividadeAluno(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId(), 0, jtAtv1.getText());
                limpaCampos();
                limpaTabela();
            }else if(jrbEnviar2.isSelected()){
                fachada.insereAtividadeAluno(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId(), 1, jtAtv2.getText());
                limpaCampos();
                limpaTabela();
            }else if(jrbEnviar3.isSelected()){
                fachada.insereAtividadeAluno(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId(), 2, jtAtv3.getText());
                limpaCampos();
                limpaTabela();
            }else if(jrbEnviar4.isSelected()){
                fachada.insereAtividadeAluno(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId(), 3, jtAtv4.getText());
                limpaCampos();
                limpaTabela();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Selecione uma Opção");
            }
        }
    }//GEN-LAST:event_jbEnviaAtividadeActionPerformed

    private void jtTurmaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTurmaKeyReleased
        // TODO add your handling code here:
        
        if(jtTurma.getSelectedRow() != -1){
            try{
                    limpaCampos();
                    ativaBotao();
                    ativaTextFild();
                    Rendimento_Escolar rendEsco = fachada.buscaRendimentoEscolar(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId());
                    jtAtv1.setText(rendEsco.getTrabalhos()[0].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[0]);
                    jtAtv2.setText(rendEsco.getTrabalhos()[1].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[1]);
                    jtAtv3.setText(rendEsco.getTrabalhos()[2].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[2]);
                    jtAtv4.setText(rendEsco.getTrabalhos()[3].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[3]);
                    
                    if(!(rendEsco.getTrabalhos()[0].equals("Não Entregue"))){
                        jtAtv1.setEditable(false);
                        jrbEnviar1.setEnabled(false);
                    }
                    if(!(rendEsco.getTrabalhos()[1].equals("Não Entregue"))){
                        jtAtv2.setEditable(false);
                        jrbEnviar2.setEnabled(false);
                    }
                    if(!(rendEsco.getTrabalhos()[2].equals("Não Entregue"))){
                        jtAtv3.setEditable(false);
                        jrbEnviar3.setEnabled(false);
                    }
                    if(!(rendEsco.getTrabalhos()[3].equals("Não Entregue"))){
                        jtAtv4.setEditable(false);
                        jrbEnviar4.setEnabled(false);
                    }
                    
            }catch(NullPointerException e){        
                
           }
        }
        
    }//GEN-LAST:event_jtTurmaKeyReleased

    private void jtTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTurmaMouseClicked
        // TODO add your handling code here:
        
        if(jtTurma.getSelectedRow() != -1){
            try{
                    limpaCampos();
                    ativaBotao();
                    ativaTextFild();
                    Rendimento_Escolar rendEsco = fachada.buscaRendimentoEscolar(aluno.getId(), fachada.buscaTurma(jtTurma.getValueAt(jtTurma.getSelectedRow(), 0).toString()).getId());
                    jtAtv1.setText(rendEsco.getTrabalhos()[0].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[0]);
                    jtAtv2.setText(rendEsco.getTrabalhos()[1].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[1]);
                    jtAtv3.setText(rendEsco.getTrabalhos()[2].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[2]);
                    jtAtv4.setText(rendEsco.getTrabalhos()[3].equals("Não Entregue") ? "" : rendEsco.getTrabalhos()[3]);
                    
                    if(!(rendEsco.getTrabalhos()[0].equals("Não Entregue"))){
                        jtAtv1.setEditable(false);
                        jrbEnviar1.setEnabled(false);
                    }
                    if(!(rendEsco.getTrabalhos()[1].equals("Não Entregue"))){
                        jtAtv2.setEditable(false);
                        jrbEnviar2.setEnabled(false);
                    }
                    if(!(rendEsco.getTrabalhos()[2].equals("Não Entregue"))){
                        jtAtv3.setEditable(false);
                        jrbEnviar3.setEnabled(false);
                    }
                    if(!(rendEsco.getTrabalhos()[3].equals("Não Entregue"))){
                        jtAtv4.setEditable(false);
                        jrbEnviar4.setEnabled(false);
                    }
                    
            }catch(NullPointerException e){        
                
           }
        }
        
    }//GEN-LAST:event_jtTurmaMouseClicked

    private void limpaTabela() {
        
        if (dtmTurmas.getRowCount() >= 0){
            for (int i=dtmTurmas.getRowCount();i > 0;i--){
                dtmTurmas.removeRow(0);
            }            
        }
    }
    
    private void limpaCampos(){
        
        jtAtv1.setText("");
        jtAtv2.setText("");
        jtAtv3.setText("");
        jtAtv4.setText("");
    }
    
    private void ativaBotao(){
        jrbEnviar1.setEnabled(true);
        jrbEnviar2.setEnabled(true);
        jrbEnviar3.setEnabled(true);
        jrbEnviar4.setEnabled(true);
    }
    
    private void ativaTextFild(){
        jtAtv1.setEnabled(true);
        jtAtv2.setEnabled(true);
        jtAtv3.setEnabled(true);
        jtAtv4.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbEnviaAtividade;
    private javax.swing.JButton jbSair;
    private javax.swing.JRadioButton jrbEnviar1;
    private javax.swing.JRadioButton jrbEnviar2;
    private javax.swing.JRadioButton jrbEnviar3;
    private javax.swing.JRadioButton jrbEnviar4;
    private javax.swing.JTextArea jtAtv1;
    private javax.swing.JTextArea jtAtv2;
    private javax.swing.JTextArea jtAtv3;
    private javax.swing.JTextArea jtAtv4;
    private javax.swing.JTable jtTurma;
    // End of variables declaration//GEN-END:variables

    
}
