/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Basicas.Aluno;
import Negocio.Fachada;

/**
 *
 * @author Arthur
 */
public class TelaPrincipalAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAluno
     * 
     * 
     */
    
    private Aluno alunoUser; 
    Fachada fachada;
    
    
    public TelaPrincipalAluno(Aluno alunoUser,Fachada fachada) {
        this.alunoUser = alunoUser; 
        this.fachada = fachada;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jtUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmConsultas = new javax.swing.JMenu();
        jmiNotas = new javax.swing.JMenuItem();
        jmiTurmas = new javax.swing.JMenuItem();
        jmiAtividades = new javax.swing.JMenuItem();
        jmMatricula = new javax.swing.JMenu();
        jmiMatricula = new javax.swing.JMenuItem();
        jmAlteracoes = new javax.swing.JMenu();
        jmiAlteracoes = new javax.swing.JMenuItem();
        jmEnvio = new javax.swing.JMenu();
        jmiEnvio = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Aluno");
        setResizable(false);
        getContentPane().setLayout(null);

        jDesktopPane1.add(jtUsuario);
        jtUsuario.setBounds(308, 64, 97, 20);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(310, 150, 73, 23);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(470, 70, 200, 70);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 750, 410);

        jmConsultas.setText("Consultas");

        jmiNotas.setText("Notas");
        jmConsultas.add(jmiNotas);

        jmiTurmas.setText("Turmas");
        jmConsultas.add(jmiTurmas);

        jmiAtividades.setText("Atividades");
        jmConsultas.add(jmiAtividades);

        jMenuBar1.add(jmConsultas);

        jmMatricula.setText("Matricula");

        jmiMatricula.setText("Turma");
        jmMatricula.add(jmiMatricula);

        jMenuBar1.add(jmMatricula);

        jmAlteracoes.setText("Alterações");

        jmiAlteracoes.setText("Turma");
        jmAlteracoes.add(jmiAlteracoes);

        jMenuBar1.add(jmAlteracoes);

        jmEnvio.setText("Envio");

        jmiEnvio.setText("Atividades");
        jmEnvio.add(jmiEnvio);

        jMenuBar1.add(jmEnvio);

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(768, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jtUsuario.setText(alunoUser.getNome());
        this.jTextPane1.setText(alunoUser.getNome());
        fachada.listaAlunos();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        TelaLogin telalogin = new TelaLogin();
        this.setVisible(false);
        telalogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                /*new TelaPrincipalAluno().setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenu jmAlteracoes;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmEnvio;
    private javax.swing.JMenu jmMatricula;
    private javax.swing.JMenuItem jmiAlteracoes;
    private javax.swing.JMenuItem jmiAtividades;
    private javax.swing.JMenuItem jmiEnvio;
    private javax.swing.JMenuItem jmiMatricula;
    private javax.swing.JMenuItem jmiNotas;
    private javax.swing.JMenuItem jmiTurmas;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
